### ISSUE TITLE
Unexpected behaviour of al-select / al-option

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#148]
I have hierarchical json structure which is splitted into three select boxes:
https://jsfiddle.net/3xmfst13/1/

Now i select a value in all three boxes.
Then i change the first box, but the third box does not change automatically.
What do i need to do?

**Comment by lega911** [comment]
> empty items to prevent errors

You can use elvis-symbol (?) for this `al-repeat="item in firstItem?.children"`, then you don't need make empty objects.

> Then i change the first box, but the third box does not change automatically.

https://jsfiddle.net/lega911/v9g5t0m5/
Look what the scope contains, al-select doesn't reset value when you change option-list. When you change firstItem, thirdItem has an old value, but select3 can't display it because it has no option for this.

You can reset it manually `al-on:change="thirdItem=null"`

I'm not sure if select should reset a value on list changing.

**Comment by lega911** [comment]
You can make like this: https://jsfiddle.net/lega911/dx2y56ja/

**Comment by dev-rke** [comment]
> You can use elvis-symbol (?) 

Great, didn't know that.

Your approach does not work as expected, when i want to use the disabled-State:
https://jsfiddle.net/gq0swbm6/

What i think about is an event which occurs when the contents of a select change.
The most simple solution would be to watch for changing of the scope variables and to fire the change-Event manually on the matching select element.

**Comment by lega911** [comment]
> The most simple solution would be to watch for changing of the scope variables

watch all variables? any variable can change select-content (via al-if / al-repeat)

> to fire the change-Event manually on the matching select element.

The problem is Select changes selectedIndex=0 (from -1) when you change select-content, it shouldn't do this (no one ask it about this)

One of solutions - using empty option:
`<option al-option="null"></option>`

Also I can extend al-option, if al-option is added/removed then it will send event to select-element to fix selectedIndex (or value), so if you use al-option for your select-content, this case will be work as expected

**Comment by lega911** [comment]
> if al-option is added/removed then it will send event to select-element to fix 

I made this fix, it seems the example works well http://jsfiddle.net/lega911/qy8xj8fe/

**Comment by lega911** [comment]
If you want a control selects first value "automatically", you can set value by `@change`
http://jsfiddle.net/lega911/ar9s0x39/

**Comment by dev-rke** [comment]
> http://jsfiddle.net/lega911/qy8xj8fe/

Works well, thank you for this fast fix! :-)

> http://jsfiddle.net/lega911/ar9s0x39/

Works well in Chrome, but not in Firefox.

**Comment by lega911** [comment]
> http://jsfiddle.net/lega911/ar9s0x39/

fixed, I expected this error in Chrome (but it worked) :)

you can see the problem in console, `@change` work before al-select, so firstItem=null
I added `.throttle-10`, now `@change` starts 10ms later, when firstItem is filled

**Comment by dev-rke** [comment]
Thank you very much! :-)
I like the throttling offset, never thought it would be so helpful.

**Comment by lega911** [comment]
I've defined priority=20 for al-select, now you don't need throttle for this. (events have priority=10)
http://jsfiddle.net/lega911/ar9s0x39/

**Comment by dev-rke** [comment]
Thank you!
Now it is really easy to use!
