### ISSUE TITLE
al-input/al-model

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#149]
> Alight has al-value, al-checked, al-radio, al-select, al-focused for two-way.

one directive for two-way?

``` html
angular 1<input ng-model="todo.text" />
angular 2<input [(ngModel)]="todo.text" />
vuejs <input v-model="message" />
aurelia.io <input type="number" value.bind="model" />
```

**Comment by dev-rke** [comment]
yes, please. :-)
But i also would it implement only as alias directive (al-bind or al-model), so it automatically chooses the correct directive (al-radio or al-value etc.).

**Comment by fend25** [comment]
but al-value and al-focus is two different directives, if merge it to one, why it wouldn't cause collision?

**Comment by dev-rke** [comment]
al-focus is an event handler, this will be al-on.focus or @focus.
al-value is accessing an attribute AND watching for a change / keydown event, so this the typical way how you can interact with an input element. So it is useful to move the default usage pattern into a model abstraction, e.g. using al-model or al-bind.

Some examples:
When changing
- textarea the property "value" is changed
- text-input the property "value" is changed
- checkbox the checked-state is changed
- select the selectedIndex is changed

This is the default change, when a user interacts with a element which he can modify.
The default attribute are the attributes i just noticed, so it is useful to map them against a simple API.
E.g.:

``` html
<input type="text" al-model="user.name" />
<textarea al-model="user.description"></textarea>
<input type="checkbox" al-model="user.gender" value="Male" />
<input type="checkbox" al-model="user.gender" value="Female" />
```

This would simplify the API for developers, because they can alwayse use al-model to bind a model to a user input element.

**Comment by lega911** [comment]
> al-focus is an event handler, this will be al-on.focus or @focus.

```
al-on:focus.twoway="model"
@focus.twoway="model"
```

?

**Comment by lega911** [comment]
```
@focus="fn()"  // element --> scope
@focus.twoway="model"  // element <--> scope
@focus.oneway="model"  // element <-- scope
```

**Comment by dev-rke** [comment]
```
@focus="fn()"  // element --> scope
al-model="model"  // element <--> scope
:focus="model"  // element <-- scope - your case would be an attribute "focus" and does not make sense in my opinion
```

**Comment by lega911** [comment]
ok, looks well

**Comment by lega911** [comment]
@focus and :focus are ready  http://jsfiddle.net/lega911/o24sn60h/

**Comment by lega911** [comment]
> al-model

done: http://jsfiddle.net/lega911/2rzLrxgr/
it proxies to other directives: https://github.com/lega911/angular-light/blob/master/src/directive/model.coffee

> al-model="model"  // element <--> scope

we can't do this for focus, because it's used for element.value

**Comment by lega911** [comment]
> al-model="model" // element <--> scope
> we can't do this for focus, because it's used for element.value

now it is al-focused="model", propose if you have an idea about it

**Comment by dev-rke** [comment]
> >  al-model
> 
> done: http://jsfiddle.net/lega911/2rzLrxgr/
>    it proxies to other directives: https://github.com/lega911/angular-light/blob/master/src/directive/model.coffee

This is great!

> now it is al-focused="model", propose if you have an idea about it

This is ok for now.
I think about using user experience states, e.g.
- focus
- hover
- active
- disabled
  But i think it does not make sense to build additional directives for the others.

**Comment by lega911** [comment]
> hover

it's interesting, al-hovered="model" ?

> active

what is it about?

**Comment by fend25** [comment]
> active

maybe click-time?

**Comment by dev-rke** [comment]
> it's interesting, al-hovered="model" ?

Maybe, the idea is to change a scope when the mouse is over an element.

> what is it about?

http://www.w3schools.com/cssref/sel_active.asp
E.g. when you click on an element. When you click on another element, the click state gets disabled (see example on w3schools).

**Comment by lega911** [comment]
hover and active are both one-way bindings - they are events, so probably we can itegrate them to `@events`, we can add modifier "model" to declare that we use model instead of js expression.

``` html
@mousehover.model="model"
@mouseactive.model="model"
```

for "hover" we can use "mouseenter + mouseleave"

``` html
@mousehover.model="model"
==
@mouseenter="model=true" @mouseleave="model=false"
```

for "active": mousedown + mouseup + mouseleave

https://jsfiddle.net/lega911/x4ggb2ct/

**Comment by dev-rke** [comment]
You asked if al-focus should be a standalone directive.
I recomended to take a look to typical CSS pseudo classes, because :focus is a pseudo class in CSS.
We do not need to implement these pseudo classes, it is just a recommendation, that al-focus does not need to be integrated in the al-model concept.
The only additional case i see would be the hover-state, but there should be no problem to apply events for this case. So it is ok to let al-focus stay standalone.
