### ISSUE TITLE
$watchGroup

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#152]

**Comment by dev-rke** [comment]
What is meant with this?
Watching for multiple variables for changes?
This is what i need currently :-)

**Comment by lega911** [comment]
> Watching for multiple variables for changes?

Yes, scope.$watchGroup(['a', 'b', 'c'], function(a, b, c) {});
I think it can be made on $watch on current version.

I will try it later

**Comment by dev-rke** [comment]
When it initially executes, will there be a call to the callback once for each attribute or will there be only one single call?
This would be the best solution for my case:

``` coffeescropt
@$watch "filter.sword", @executeFilter
@$watch "filter.productGroup", @executeFilter
@$watch "filter.categorie", @executeFilter
@$watch "filter.size", @executeFilter
@$watch "filter.quality", @executeFilter
```

There are 5 calls to @executeFilter on initializing the application.
When using 

``` coffeescript
@$watchGroup ['filter.sword', 'filter.productGroup', 'filter.categorie', 'filter.size', 'filter.quality'], @executeFilter
```

i assume there would be only one single call, because i "install" only a single group watcher.
Is my assumption correct?

**Comment by lega911** [comment]
> Is my assumption correct?

yes

**Comment by lega911** [comment]
it can work in similar way: http://jsfiddle.net/lega911/cmkn1u7x/

**Comment by dev-rke** [comment]
> it can work in similar way: http://jsfiddle.net/lega911/cmkn1u7x/

Will there be a $watchGroup function in near future or should i go for an own implementation?
Both ways are ok for me, just like to know if i should wait for new version.

**Comment by lega911** [comment]
I want to take it into alight. Suggest me better API

I think makeing a group for $watch is more flexible, because you are able to choose type of watcher (array/deep) for every watcher, and you can join new watchers or stop old ones any time.

``` js
  var group = scope.$watchGroup(callback);

  scope.$watch("filter.sword", group);
  scope.$watch("filter.productGroup", group);
```

On the other hand I can check input, if you give me array as first argument:

``` js
scope.$watchGroup(["filter.sword", "filter.productGroup"], callback);
```

ok, it looks well

**Comment by lega911** [comment]
done, 
http://jsfiddle.net/lega911/8om4ur4f/
http://jsfiddle.net/lega911/8nvb24uy/

**Comment by dev-rke** [comment]
What about extending scope.$watch and check if the first parameter is an array:
`scope.$watch(["filter.sword", "filter.productGroup"], callback);`
This would reduce methods which have to be injected into each scope.

Your first approach (https://jsfiddle.net/lega911/8om4ur4f/) is a bit more flexible, because i can add items to a group dynamically. But i cannot remove them from the group. So i think i have no advantage to a simple array. I think the best implementation is to check if the first parameter of scope.$watch is an array.

**Comment by lega911** [comment]
> But i cannot remove them from the group

Why? You can: https://jsfiddle.net/lega911/c3bwuqhr/

> because i can add items to a group dynamically

You can add dynamically in both cases: http://jsfiddle.net/lega911/8nvb24uy/

**Comment by dev-rke** [comment]
This is cool!
Really cool!

Thank you! :-)

By the way: it is hard to use new features when they are not released.
I switched to download the compiled build from website, instead of updating bower, because bower builds often are a bit outdated.
I won't link to the pre-build library on your website, because when there are feature or API changes my implementation may not work anymore. And as it is a productive environment, it needs to be stable.
Do you think we can optimize this process a bit (e.g. one release per week)?

**Comment by lega911** [comment]
> e.g. one release per week

per week is ok, last one was 2 days ago

**Comment by dev-rke** [comment]
Yes, i understand you do not want to release for each bugfix or feature extension, but as we are in a development phase it might be useful to make smaller releases. Thank you. :-)

**Comment by dev-rke** [comment]
I think we can close this, group watching works very well.
