### ISSUE TITLE
[Suggestion] have ng1 like bindings

### ISSUE THREAD

**Issue by sp90** [lega911/angular-light#219]
Super interesting project, i do believe that having ng1 like bindings, for people to switch over easily from ng1

**Comment by lega911** [comment]
> ng1 like bindings

like ng-click, ng-disabled ?

**Comment by sp90** [comment]
Yes 👍 , is there a reason why this isn't the case?

**Comment by lega911** [comment]
It was in previouse versions 0.10, 0.8 ..., now it is possible to build with option "compatibility".

In last version instead of bunch of directives like `al-click`, `al-mousemove`..., we have one directive for any event:  `al-on`, and you can choose any event: `al-on.click, al-on.mousemove, al-on.mycustomevent ...`, or short version (alise) `@click, @mousemove`, also you can attach throttle, debounce and other modifiers http://angular-light.readthedocs.io/en/latest/events.html
