### ISSUE TITLE
Help with components

### ISSUE THREAD

**Issue by rumkin** [lega911/angular-light#224]
I want to create component. Let's call it user-editor. It should has single param `user`. This param should react on changes both inside and outside of component. I'm try to do something like this:

```javascript
alight.component('user-editor', (scope, el, env) => {
    return {
        props: ['user'],
        template: '<input type="text" al-model="user.name"/>',
    };
});

alight.bootstrap('[al-app]', {
    user: {name: 'John'},
});
```

```html
<body>
    <div al-app>
        <user-editor :user="user"></user-editor>
        <input type="text" al-model="user.name"/>
    </div>
</body>
```

http://jsfiddle.net/mmty3enh/2/

I've got an error:
```
[Error] $scan, error in expression: user.name (3)
"undefined is not an object (evaluating '$$scope.user.name')"
{src: "user.name", scope: {}, locals: {}}
"anonymous
m@https://angularlight.org/bin/alight_0.14.last.min.js:6:9723
digest@https://angularlight.org/bin/alight_0.14.last.min.js:6:10683
bind@https://angularlight.org/bin/alight_0.14.last.min.js:6:26235
bootstrap@https://angularlight.org/bin/alight_0.14.last.min.js:6:27647
bootstrap@https://angularlight.org/bin/alight_0.14.last.min.js:6:27333
bootstrap@https://angularlight.org/bin/alight_0.14.last.min.js:6:26841
e@https://angularlight.org/bin/alight_0.14.last.min.js:6:4214"
	m (alight_0.14.last.min.js:6:10007)
	digest (alight_0.14.last.min.js:6:10684)
	bind (alight_0.14.last.min.js:6:26236)
	bootstrap (alight_0.14.last.min.js:6:27648)
	bootstrap (alight_0.14.last.min.js:6:27334)
	bootstrap (alight_0.14.last.min.js:6:26842)
	e (alight_0.14.last.min.js:6:4215)
```

**Comment by lega911** [comment]
Hello!

First problem is [al-app] starts automatically, and you start alight.bootstrap manually, so 2 apps are started twice on the same DOM.

Component is like isolated sub application, so application doesn't have access into body of component and vice-versa.
You can use property to put data into a component, you can call api of component, component can send event to an app.

Second problem, you pass object instead of simple type (string/integer/...), and change data inside of it. you need to use deep watch to detect changes inside of the object.
by default you can skip keyword "props", and all property will be attached automatically

example for simple type (string) + auto props: http://jsfiddle.net/lega911/xphovz3n/

example with deep watch: http://jsfiddle.net/lega911/247kx0bf/

**Comment by lega911** [comment]
instead of alight.bootstrap(...) you can use alight(...)

**Comment by lega911** [comment]
> First problem is [al-app] starts automatically, and you start alight.bootstrap manually, so 2 apps are started twice on the same DOM.

[al-app] started without data "user.name", so it gives exception "undefined is not an object" becuse user == undefined

alight.bootstrap doesn't work in your exmaple, because it started in section <head>, when DOM is not exists yet, need to switch to "onLoad" or "on DOM ready"

**Comment by rumkin** [comment]
Thanks. It helps
